DROP TABLE tickets;
DROP TABLE customers;
DROP TABLE films;

CREATE TABLE customers (
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255),
  funds SMALLINT
);

CREATE TABLE films (
  id SERIAL4 PRIMARY KEY,
  title VARCHAR(255),
  price SMALLINT
);

CREATE TABLE tickets (
  id SERIAL4 PRIMARY KEY,
  customer_id SMALLINT REFERENCES customers(id) ON DELETE CASCADE,
  film_id SMALLINT REFERENCES films(id) ON DELETE CASCADE
);
